# Generated by Django 5.0 on 2024-01-27 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('contract_number', models.CharField(max_length=11)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('Laptop', 'Laptop'), ('Headphone', 'Headphone'), ('Mobile', 'Mobile'), ('Sim', 'Sim')], max_length=40)),
                ('handover_time', models.DateTimeField(auto_now=True)),
                ('Receive_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.person')),
            ],
        ),
    ]
