# Generated by Django 5.0 on 2024-01-27 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_receive_time_items_receive_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='belongs_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_owned', to='app.person'),
        ),
    ]
