# Generated by Django 5.0 on 2024-01-27 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_items_belongs_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='belongs_to',
        ),
    ]
