# Generated by Django 5.0 on 2024-01-27 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_items_belongs_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_owned', to='app.person'),
        ),
    ]
