# Generated by Django 5.0 on 2024-01-27 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='sumitting_time_condition',
            field=models.TextField(null=True),
        ),
    ]
