# Generated by Django 5.0 on 2024-01-28 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_items_sumitting_time_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='sumitting_time_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
