# Generated by Django 5.0 on 2024-01-28 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_historicalitems_historicalperson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalperson',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalItems',
        ),
        migrations.DeleteModel(
            name='HistoricalPerson',
        ),
    ]
