# Generated by Django 5.0 on 2024-01-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_historicalitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitems',
            name='sumitting_time_condition',
        ),
        migrations.RemoveField(
            model_name='items',
            name='sumitting_time_condition',
        ),
        migrations.AddField(
            model_name='historicalitems',
            name='handover_time_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalitems',
            name='submitting_time_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='handover_time_condition',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='submitting_time_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
