# Generated by Django 5.0 on 2024-01-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_historicalitems_sumitting_time_condition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalitems',
            name='handover_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='items',
            name='handover_time',
            field=models.DateTimeField(),
        ),
    ]
